### ISSUE TITLE
rfiddl.py

### ISSUE THREAD

**Issue by Dinsmoor** [cameronkempster/RasPiDoorLock#1]
rfiddl.py looks a lot like the example here: https://github.com/mxgxw/MFRC522-python/blob/master/Read.py yet I see no attribution to the author mxgxw.

**Comment by cameronkempster** [comment]
How would you suggest i do this?

**Comment by Dinsmoor** [comment]
Add an attribution to the author, mxgxw, to give them credit for their code.
